### ISSUE TITLE
LoadError

### ISSUE THREAD

**Issue by hashfunktion** [marcofl/check_apc_ats#1]
Hi!

First big thanks for this check plugin - it´s great!
But i have a LoadError when i use the check.
I have installed ruby 1.8.7, rubygems and snmp-gem 1.2.0
Error:
 ./check_apc_ats:23:in `require': no such file to load -- snmp (LoadError)
        from ./check_apc_ats:23

I have create a pull request with a fix that have work for me.

Kind regards,
Jesse

**Comment by marcofl** [comment]
Unfortunately I somehow did not see this pull request until now. Merged, thank you.
